calcit.edn, package.json, shadow-cljs.edn, src/app/updater/writer.cljs, yarn.lock
Now pressing `Command k` will delete bookmarks too when `pointer` equals 0.
=> allow removing top-most bookmark

calcit.edn, src/app/connection.cljs
...or there would be an error.
=> detect socket existence before calling send!

calcit.edn, package.json, shadow-cljs.edn, src/app/client.cljs, src/app/server.cljs, src/app/util/compile.cljs, yarn.lock
My fault not to confirm checking saving event. `:effect/save-files` action was lost.
=> fix save-files action

calcit.edn, package.json, shadow-cljs.edn, src/app/client.cljs, yarn.lock
Clear drafting states on reset, otherwise drafts would mess up the edited branches.
=> upgrade deps; also clear editing states on reset-files

README.md
=> update README to promote

calcit.edn, src/app/comp/page_files.cljs, src/app/style.cljs
Buttons are now in a separated line.
=> small style changes in file buttons

calcit.edn, package.json, shadow-cljs.edn, src/app/comp/container.cljs, src/app/comp/messages.cljs, src/app/comp/repl_page.cljs, src/app/repl.cljs, src/app/server.cljs, src/app/style.cljs, src/app/theme/star_trail.cljs, yarn.lock
=> upgrade styles; colorize nil

calcit.edn, package.json, src/app/comp/page_editor.cljs, src/app/updater/ir.cljs
`(case ... (:else db))` caused empty return value. Changed both sides to fix the problem.
=> fix ir/delete-entry on nil

calcit.edn, package.json, shadow-cljs.edn, src/app/comp/changed_files.cljs, src/app/comp/changed_info.cljs, yarn.lock
Clear editing states to fix text inconsistency after resetting.
=> clear states when reset happens; alpha release

calcit.edn, entry/main.css, src/app/comp/about.cljs, src/app/comp/container.cljs, src/app/util/dom.cljs
=> get a more intuitive offline page

calcit.edn, package.json, src/app/server.cljs
`delay!` takes time in seconds. So 20ms should be `0.02`.
=> fix delay time in watch handler; alpha release

calcit.edn, package.json, src/app/repl.cljs
Due to change in upstream https://github.com/thheller/shadow-cljs/issues/524#issuecomment-513552218
=> change path to .shadow-cljs/nrepl.port ; alpha release

calcit.edn, package.json, shadow-cljs.edn, src/app/client.cljs, src/app/repl.cljs, src/app/server.cljs, src/app/util.cljs, src/app/util/compile.cljs, src/app/util/env.cljs
Plus: added support for detecting `:default` methods in importing modules.
=> syntax updates with js-interop; alpha release

calcit.cirru, src/app/comp/bookmark.cljs, src/app/comp/container.cljs, src/app/comp/header.cljs, src/app/comp/page_files.cljs, src/app/comp/search.cljs
=> refining list style of files and search results

calcit.cirru, package.json, src/app/comp/page_editor.cljs, src/app/updater.cljs, src/app/updater/ir.cljs
`ir/expr-replace` replace tokens in branch with a new token.
=> add replace button; alpha release

.github/workflows/upload.yaml, calcit.cirru, package.json, src/app/client_util.cljs, src/app/comp/leaf.cljs, src/app/util.cljs, src/app/util/compile.cljs
Should fix on https://github.com/Cirru/calcit-editor/pull/52 .
=> trying to fix reference to now! , which has influences on parse-url

README.md
Please review https://github.com/Cirru/calcit-editor/blob/improving-readme/README.md .
=> send more straight impressions to visitors

calcit.cirru, package.json, src/app/comp/changed_files.cljs, src/app/comp/changed_info.cljs, src/app/server.cljs, src/app/updater/writer.cljs, src/app/util/compile.cljs
Added a button for saving a single namespace to disk. Code could be messy.
=> add entries for saving by a single file

calcit.cirru, src/app/comp/changed_files.cljs, src/app/comp/changed_info.cljs, src/app/comp/page_editor.cljs, src/app/comp/page_files.cljs
Makes use of abstraction in https://github.com/Respo/alerts/#use-confirm .
=> refactor: replace comp-confirm code

calcit.cirru, shadow-cljs.edn, src/app/comp/header.cljs
Based on https://github.com/Respo/alerts/pull/27 .
Make alerts syntax a bit easier.
=> upgrade alerts component

calcit.cirru, package.json, src/app/comp/page_files.cljs, src/app/schema.cljs, src/app/twig/page_files.cljs, src/app/updater.cljs, src/app/updater/ir.cljs, src/app/util/compile.cljs
There are 3 common used file extensions for different purposes...
Edge cases not handled yet.
=> initial support for configuring per file extension

calcit.cirru, package.json, src/app/comp/expr.cljs, src/app/comp/leaf.cljs, src/app/comp/page_editor.cljs, src/app/comp/replace_name.cljs, src/app/twig/page_editor.cljs
Displaying imported variables/ns and defined functions/variables for picker.
Also the tip can be closed by ESC now.
=> display suggests from ns and defs in picker mode

calcit.cirru, package.json, shadow-cljs.edn, src/app/repl.cljs, yarn.lock
=> display eval results in a very rough way

calcit.cirru, package.json, src/app/comp/page_editor.cljs, src/app/comp/repl_preview.cljs, src/app/repl.cljs, src/app/twig/container.cljs, src/app/twig/page_editor.cljs, src/app/updater.cljs, src/app/updater/repl.cljs
Now REPL preview is displayed at right top corner.
=> add a repl preview card

README.md, calcit.cirru, package.json, src/app/util.cljs, src/app/util/compile.cljs
`compact.cirru` and `.compact-inc.cirru` would be used in future projects.
=> write compact-inc data

calcit.cirru, package.json, shadow-cljs.edn, src/app/comp/page_editor.cljs, yarn.lock
Filter hint with currently typing string, for example "comp":
=> try to filter names in picker mode

calcit.cirru, package.json, shadow-cljs.edn, src/app/comp/configs.cljs, src/app/comp/container.cljs, src/app/comp/header.cljs, src/app/twig/container.cljs, src/app/updater.cljs, src/app/updater/configs.cljs
=> add UI for setting version

calcit.cirru, package.json, src/app/comp/configs.cljs, yarn.lock
=> support editing modules field in configs

.gitattributes, calcit.cirru, package.json, src/app/comp/bookmark.cljs, src/app/comp/configs.cljs, src/app/comp/container.cljs, src/app/comp/header.cljs, src/app/comp/page_editor.cljs, yarn.lock
=> refine UI to reduce spaces occupation

calcit.cirru, package.json, src/app/comp/draft_box.cljs
since there's no type checking, I forgot to check other code that triggering the same action. turned into this bug.
=> fix missing leaf op
